exp_name: "igpt_cifar100_baseline"

model:
  type: igpt
  image_size: 32
  in_channels: 3
  vocab_size: 256
  d_model: 128
  N: 2
  h: 4
  d_ff: 512
  dropout: 0.1

data:
  train: datasets/
  valid: datasets/
  patch_size: null
  num_workers: 4

train:
  amp_dtype: "fp16" # 4090: fp16; H800/H20: bf16
  batch_size: 64 # 4090: 64; H800/H20: 256
  grad_accum_steps: 8 
  lr: 3e-4
  eps: 1e-8
  epochs: 100
  log_freq: 100
  clip_max_norm: 1.0
  lmbda: 0.01
  lr_milestones: [60, 90]
  lr_gamma: 0.1

eval:
  interval: 5

checkpoint:
  save_interval: 10