exp_name: "igpt_experiment"

model:
  type: igpt
  image_size: 32
  in_channels: 3
  vocab_size: 256
  d_model: 256
  N: 6
  h: 8
  d_ff: 1024
  dropout: 0.1

data:
  train: datasets/cifar-100-python/train
  valid: datasets/cifar-100-python/test
  patch_size: null
  num_workers: 4

train:
  batch_size: 64
  lr: 3e-4
  epochs: 30
  log_freq: 50
  clip_max_norm: 1.0

eval:
  interval: 1

checkpoint:
  save_interval: 5